# Generated by Django 5.2.9 on 2025-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=50, help_text='Percentage you’ve studied/learned this skill (0–100).'),
        ),
    ]
