# Generated by Django 5.2.9 on 2025-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_proficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='year',
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='issued_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certification',
            name='provider',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
