# Generated by Django 5.2.9 on 2025-12-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resume_visitorcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='page',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
