# Generated by Django 5.2.9 on 2025-12-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_visitorcount_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
