# Generated by Django 5.2.9 on 2025-12-15 07:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_visitorcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificate'),
        ),
    ]
